import { Router } from "express";
import { createAdminCategory, getAdminCurrencyRates, getFinancialReport, getSellerEntitlements, listAdminAudit, listAdminCategories, listAdminPlans, recordAdminRefund, startSellerImpersonation, stopSellerImpersonation, updateAdminCurrencyRates, updateAdminPlan, getAdminOperationsOverview, getSeller360, updateSellerCommission, getSellerPayoutReport, recordSellerPayout, exportAdminData, listAdminStaff, setAdminStaffRole, requestAdminStepUp, verifyAdminStepUp } from "../controller/admin.controller";
import { auth } from "../middleware/auth.middleware";
import requireAdminStepUp from "../middleware/admin-step-up.middleware";

const adminRoutes = Router();
adminRoutes.post("/admin/step-up/request", auth, requestAdminStepUp);
adminRoutes.post("/admin/step-up/verify", auth, verifyAdminStepUp);
adminRoutes.get("/admin/audit", auth, listAdminAudit);
adminRoutes.get("/admin/categories", auth, listAdminCategories);
adminRoutes.post("/admin/categories", auth, requireAdminStepUp, createAdminCategory);
adminRoutes.get("/admin/plans", auth, listAdminPlans);
adminRoutes.put("/admin/plans/:key", auth, requireAdminStepUp, updateAdminPlan);
adminRoutes.get("/seller/entitlements", auth, getSellerEntitlements);
adminRoutes.post("/admin/impersonation/:userId", auth, requireAdminStepUp, startSellerImpersonation);
adminRoutes.delete("/admin/impersonation", auth, stopSellerImpersonation);
adminRoutes.get("/admin/finance", auth, getFinancialReport);
adminRoutes.post("/admin/finance/refunds", auth, requireAdminStepUp, recordAdminRefund);
adminRoutes.get("/admin/currency-rates", auth, getAdminCurrencyRates);
adminRoutes.put("/admin/currency-rates", auth, requireAdminStepUp, updateAdminCurrencyRates);
adminRoutes.get("/admin/operations-overview", auth, getAdminOperationsOverview);
adminRoutes.get("/admin/sellers/:sellerId/360", auth, getSeller360);
adminRoutes.put("/admin/sellers/:sellerId/commission", auth, requireAdminStepUp, updateSellerCommission);
adminRoutes.get("/admin/finance/seller-payouts", auth, getSellerPayoutReport);
adminRoutes.post("/admin/finance/seller-payouts/:shopId", auth, requireAdminStepUp, recordSellerPayout);
adminRoutes.get("/admin/export", auth, exportAdminData);
adminRoutes.get("/admin/staff", auth, listAdminStaff);
adminRoutes.put("/admin/staff/:userId", auth, requireAdminStepUp, setAdminStaffRole);
export default adminRoutes;
